### ISSUE TITLE
Shift+Click on icon causes JavaScript Error in OS X 10.11.3

### ISSUE THREAD

**Issue by tdlm** [madebybright/te#10]
`Uncaught Exception:
TypeError: Cannot read property 'openDevTools' of undefined
    at Tray.click (/Applications/Nimble.app/Contents/Resources/app/index.js:115:22)
    at emitTwo (events.js:92:20)
    at Tray.emit (events.js:172:7)`

**Comment by ethel-dev** [comment]
This is a currently unavoidable issue. Here's the fix: make sure Nimble has loaded first by opening it and waiting for it to start up, then try shift clicking.

**Comment by tdlm** [comment]
@soops That didn't work. Still errors out.

**Comment by jshdm** [comment]
Does it provide the same error if you try loading it first? Just confirming, you'll have to wait until Nimble's content is completely loaded before closing Nimble and shift-clicking.

![nimble-shift-click](https://cloud.githubusercontent.com/assets/4617414/12906493/af36d63e-ce95-11e5-9b95-25be880ecd4d.gif)

We're working on fixing this issue so Nimble is automatically loaded beforehand, although as shift-click provides nothing of value to the average user this isn't top priority at the moment.

**Comment by ethel-dev** [comment]
Fixed. You should get any errors anymore! I've made it so Devtools is only openable after Nimble is loaded, and Nimble autoloads a bit before you open it to speed things up.

**Comment by jshdm** [comment]
*should not :wink:
