### ISSUE TITLE
It doesn't seem to be able to answer anything

### ISSUE THREAD

**Issue by scalp42** [madebybright/te#11]
![](https://i.imgur.com/i5ZFyx7.png)

**Comment by ethel-dev** [comment]
We are extremely sorry. Our recent spike in publicity overloaded our
WolframAlpha requests. We are all currently in contact with Wolfram to work
this out

**Comment by shiruken** [comment]
Any chance of allowing users to input a personal Wolfram Alpha API key?

**Comment by scalp42** [comment]
Oh please don't be sorry, no worries :smile: 

Just wanted to test, hopefully it helps!

**Comment by ethel-dev** [comment]
Thanks for the support!

**Comment by betrisey** [comment]
@shiruken  I think you can do it with your own backend server https://github.com/madebybright/NimbleBackend and then edit this file https://github.com/madebybright/Nimble/blob/master/src/js/script.js

**Comment by shiruken** [comment]
@betrisey I just tried installing and running the code from this repo with a custom API key and it appears to work (without requiring their backend apparently). I believe the non-commercial API limit is only 2000 queries per month so it's no wonder they've exceeded it after today's press.

**Comment by ethel-dev** [comment]
You can add your own key as described in the read me. We don't use our
Backend servers anymore, so just get a key and use it!

**Comment by ethel-dev** [comment]
Also, thank you for understanding. Unfortunately Wolfram can take a bit to respond, but we are trying our best to get back to normal!

**Comment by xeor** [comment]
Any news on this?

**Comment by ethel-dev** [comment]
Not yet. We're in talks with Wolfram still but closer to the key than in the beginning. Sorry for the nuisance! We're trying our best as always!

**Comment by jshdm** [comment]
Fixed in [ae0e469](https://github.com/madebybright/Nimble/commit/44f94e273cfd1ed1dbfc64c96fc7ed6da63edd08).
