### ISSUE TITLE
Load results in full WolframAlpha website

### ISSUE THREAD

**Issue by shiruken** [madebybright/te#12]
It would be useful to have an option to open the search results in the full Wolfram Alpha website. Maybe display a little external link icon alongside the inline results.

**Comment by ethel-dev** [comment]
This is implemented :)
You can copy the wolfram link in the "Edit" menu, accessible by right
clicking.

Not yet implemented as a clickable link though, should come soon.

**Comment by shiruken** [comment]
@soops Ah I didn't even realize that that menu existed!

**Comment by ethel-dev** [comment]
Yeah, lots of good stuff in there!

**Comment by ethel-dev** [comment]
My favorite option is moving Nimble to the center, by the way!
