### ISSUE TITLE
Crashes on every right click

### ISSUE THREAD

**Issue by DeeeeLAN** [madebybright/te#13]
There isn't much else to say about it.  It will run fine, then I right click and it closes itself out without any notifications.

**Comment by jshdm** [comment]
This is the expected result. [Right clicking Nimble will quit it.](https://github.com/madebybright/Nimble/blob/master/index.js#L181)

We're working on adding a context menu (possibly an about, preferences, and quit) on right click to clear up this confusion, as we've had a few users report to us confused about this.
