### ISSUE TITLE
Nimble is not working

### ISSUE THREAD

**Issue by GeorgeDrg** [madebybright/te#15]
Hey, 

At the moment, Nimble doesn't seem to work. The menu bar doesn't function, in addition, the Shuf+Command+=  does not open Nimble.

**Comment by ethel-dev** [comment]
Thanks! What I would try is right clicking the menubar icon, which should close Nimble. After that, reopen Nimble from the Applications folder, and try again. I'm not really sure what the issue is, but hopefully we can get it figured out!

**Comment by ethel-dev** [comment]
Also, at the moment, Nimble is not in a functioning state out of the box because we are currently negotiating with Wolfram|Alpha about pricing. This should clear up ASAP, but there are fixes around right now.

https://medium.com/@brightco/roadblocks-ab6524617017#.bupihkrrs

**Comment by tkothe** [comment]
@soops Cool, the instructions on the medium post helped me getting Nimble to work. Great stuff! 

I'd say it would be extremely helpful if you put that on your website http://madebybright.com/ . I am raising a corresponding issue in [madebybright/madebybright.github.io](https://github.com/madebybright/madebybright.github.io) and who knows, maybe I will even submit a PR.

Cheers!

**Comment by jshdm** [comment]
> I'd say it would be extremely helpful if you put that on your website

We're about to finish a deal with Wolfram that will effectively fix Nimble's state of dysfunction, so we're going to wait it out for the time being. If it persists any longer we'll definitely take your suggestion.

**Comment by jshdm** [comment]
Fixed in [ae0e469](https://github.com/madebybright/Nimble/commit/44f94e273cfd1ed1dbfc64c96fc7ed6da63edd08).
