### ISSUE TITLE
Shortcut support

### ISSUE THREAD

**Issue by vagelim** [madebybright/te#17]
Feature request:
It would be great if you could invoke Nimble with a shortcut, instead of having to use the mouse.

**Comment by jshdm** [comment]
A global hotkey to toggle Nimble was added in [v1.0.3](https://github.com/madebybright/Nimble/releases/tag/1.0.3). You can activate it with <kbd>⌘</kbd> <kbd>Shift</kbd> <kbd>=</kbd>.
