### ISSUE TITLE
Right clicking quits (crashes?) Nimble

### ISSUE THREAD

**Issue by turrball** [madebybright/te#19]
Congratulations on 1.0.4! Glad to see it working. Clicking Nimble on the menubar once to invoke it and right clicking it crashes or quits the app. OS X El Capitan 10.11.4.

**Comment by ethel-dev** [comment]
it quits the app, we are fixing it tonight. this is intentional :)

**Comment by turrball** [comment]
Oh okay :) Btw, is it possible to open the corresponding Wolfram Alpha page on the default web browser for a search query to see more interpretations? And would it be possible (even if in the future) to invoke Nimble with a keyboard shortcut? These will be super helpful!

**Comment by jshdm** [comment]
We'll add an option to open the W|A page in the browser soon! Thanks for the suggestion :smile: For the time being, `↑⌘L` will copy the corresponding query link to your clipboard, so you can paste it manually into the browser of your choice.

As for the shortcut to invoke Nimble, `↑⌘=` will work globally.

**Comment by jshdm** [comment]
Fixed in [ae0e469](https://github.com/madebybright/Nimble/commit/44f94e273cfd1ed1dbfc64c96fc7ed6da63edd08).
