### ISSUE TITLE
Unicode interpretation

### ISSUE THREAD

**Issue by ghost** [madebybright/te#6]
To reproduce: 
1. Enter "700 GBP in Chinese yuan" 

Expected: Returns "￥6651.86 (Chinese yuan)"
Result: Returns "\:ffe56651.86 (Chinese yuan)"

Note how it uses the fullwidth yen sign instead of the normal yen sign, which renders perfectly.

**Comment by ethel-dev** [comment]
Fixed with the new backend merge.
