### ISSUE TITLE
Support tables

### ISSUE THREAD

**Issue by ghost** [madebybright/te#7]
To reproduce:
1. Enter "Eiffel Tower, Empire State Building"

Expected: Returns a neatly formatted table comparing the two buildings.
Result: Returns the following:

```
| Eiffel Tower | Empire State Building\ncities | Paris, Ile-de-France, France | New York City, New York, United States\nheight | 324 meters  (city rank: 1st  |  national rank: 1st  |  world rank: 54th) | 381 meters  (city rank: 2nd  |  national rank: 4th  |  world rank: 26th)\nfloors | 3 | 102\nfloor area |  | 254000 m^2  (square meters)\ncompletion date | 1889 (127 years ago) | 1931 (85 years ago)
```

The table is presented so that every newline is a row (i.e.: the amount of rows = the amount of `\n`s + 1) and that every pipe is a column separator (i.e.: the amount of columns = the amount of `|`s + 1).

**Comment by ethel-dev** [comment]
done. images took care of this.

**Comment by ghost** [comment]
tru tru
